#! /bin/sh

if [ -e "$BSPWM_LAYOUT" ] ; then
    bspc restore_layout "$BSPWM_LAYOUT"
    rm "$BSPWM_LAYOUT"
else
    bspc adopt_orphans
fi

if [ -e "$BSPWM_HISTORY" ] ; then
    bspc restore_history "$BSPWM_HISTORY"
    rm "$BSPWM_HISTORY"
fi
