:man source:   Bspwm
:man version:  {revnumber}
:man manual:   Bspwm Manual

bspwm(1)
========

Name
----

bspwm - Binary space partitioning window manager

Synopsis
--------

*bspwm* [*-h*|*-v*|*-c* 'CONFIG_PATH']

*bspc* 'COMMAND' ['ARGUMENTS']

Description
-----------

*bspwm* is a tiling window manager that represents windows as the leaves of a full binary tree.

It is controlled and configured via *bspc*.


Options
-------

*-h*::
	Print the synopsis and exit.

*-v*::
	Print the version and exit.

*-c* 'CONFIG_PATH'::
	Use the given configuration file.

Common Definitions
------------------

----
DIR         := left | right | up | down
CYCLE_DIR   := next | prev
----

Selectors
---------

Selectors are used to select a target window, desktop, or monitor. A selector
can either describe the target relatively or name it globally.

Descriptive (relative) selectors consist of a primary selector and any number
of non-conflicting modifiers as follows:

	PRIMARY_SELECTOR[.MODIFIER]*

For obvious reasons, neither desktop nor monitor names may be valid descriptive
selectors.

An exclamation mark can be prepended to certain modifiers in order to reverse their meaning.

Window
~~~~~~

Select a window.

----
WINDOW_SEL := (<window_id>|DIR|CYCLE_DIR|biggest|last|focused|older|newer)[.[!]automatic][.[!](tiled|pseudo_tiled|floating|fullscreen)][.[!](below|normal|above)][.[!]local][.[!]same_class][.[!]focused][.[!](urgent|sticky|private|locked)]
----

Primary Selectors
^^^^^^^^^^^^^^^^^

'DIR'::
	Selects the window in the given (spacial) direction relative to the active window.

'CYCLE_DIR'::
	Selects the window in the given (cyclic) direction.

biggest::
	Selects the biggest window on the current desktop.

last::
	Selects the previously focused window.

focused::
	Selects the currently focused window.

older::
	Selects the window older than the focused window in the history.

newer::
	Selects the window newer than the focused window in the history.

Modifiers
^^^^^^^^^

[!](tiled|pseudo_tiled|floating|fullscreen)::
	Only consider windows having or not having the given state.

[!]automatic::
	Only consider windows in automatic or manual insertion mode.

[!]focused::
	Only consider focused or unfocused windows.

[!]same_class::
	Only consider windows that have or don't have the same class as the current window.

[!]local::
	Only consider windows in or not in the current desktop.

[!](private|urgent|sticky|locked)::
	Only consider windows that have or don't have the given flag set.

[!](below|normal|above)::
	Only consider windows in or not in the given layer.

Desktop
~~~~~~~

Select a desktop.

----
DESKTOP_SEL := (<desktop_name>|[MONITOR_SEL:](focused|^<n>)CYCLE_DIR|last|older|newer)[.[!]occupied][.[!]focused][.[!]urgent][.[!]local]
----

Primary Selectors
^^^^^^^^^^^^^^^^^

<desktop_name>::
	Selects the desktop with the given name.

^<n>::
	Selects the nth desktop.

'CYCLE_DIR'::
	Selects the desktop in the given direction relative to the active desktop.

last::
	Selects the previously focused desktop.

focused::
	Selects the currently focused desktop.

older::
	Selects the desktop older than the focused desktop in the history.

newer::
	Selects the desktop newer than the focused desktop in the history.

Modifiers
^^^^^^^^^

[!]occupied::
	Only consider occupied or free desktops.

[!]focused::
	Only consider focused or unfocused desktops.

[!]urgent::
	Only consider urgent or non urgent desktops.

[!]local::
	Only consider inside or outside of the current monitor.

Monitor
~~~~~~~

Select a monitor.

----
MONITOR_SEL := (<monitor_name>|^<n>|DIR|CYCLE_DIR|last|primary|focused|older|newer)[.[!]occupied][.[!]focused]
----

Primary Selectors
^^^^^^^^^^^^^^^^^

<monitor_name>::
	Selects the monitor with the given name.

^<n>::
	Selects the nth monitor.

'DIR'::
	Selects the monitor in the given (spacial) direction relative to the active monitor.

'CYCLE_DIR'::
	Selects the monitor in the given (cyclic) direction relative to the active monitor.

primary::
	Selects the primary monitor.

last::
	Selects the previously focused monitor.

focused::
	Selects the currently focused monitor.

older::
	Selects the monitor older than the focused monitor in the history.

newer::
	Selects the monitor newer than the focused monitor in the history.

Modifiers
^^^^^^^^^

[!]occupied::
	Only consider monitors where the focused desktop is occupied or free.

[!]focused::
	Only consider focused or unfocused monitors.


Window States
-------------

tiled::
	Its size and position are determined by the splitting type and ratio of each node of its path in the window tree.

pseudo_tiled::
	Has an unrestricted size while being centered in its tiling space.

floating::
	Can be moved/resized freely. Although it doesn't occupy any tiling space, it is still part of the window tree.

fullscreen::
	Fills its monitor rectangle and has no borders. It is send in the ABOVE layer by default.


Window Flags
-------------

locked::
	Ignores the *window --close* message.

sticky::
	Stays in the focused desktop of its monitor.

private::
	Tries to keep the same tiling position/size.

urgent::
	Has its urgency hint set. This flag is set externally.


Stacking Layers
--------------

There's three stacking layers: BELOW, NORMAL and ABOVE.

In each layer, the window are orderered as follow: tiled & pseudo-tiled < fullscreen < floating.


Commands
--------

Window
~~~~~~

General Syntax
^^^^^^^^^^^^^^

window ['WINDOW_SEL'] 'OPTIONS'

Options
^^^^^^^
*-f*, *--focus* ['WINDOW_SEL']::
	Focus the selected or given window.

*-a*, *--activate* ['WINDOW_SEL']::
	Activate the selected or given window.

*-d*, *--to-desktop* 'DESKTOP_SEL'::
	Send the selected window to the given desktop.

*-m*, *--to-monitor* 'MONITOR_SEL'::
	Send the selected window to the given monitor.

*-w*, *--to-window* 'WINDOW_SEL'::
	Transplant the selected window to the given window.

*-s*, *--swap* 'WINDOW_SEL'::
	Swap the selected window with the given window.

*-p*, *--presel* 'DIR'|cancel::
	Preselect the splitting area of the selected window (or cancel the preselection).

*-r*, *--ratio* 'RATIO'::
	Set the splitting ratio of the selected window (0 < 'RATIO' < 1).

*-e*, *--edge* 'DIR' 'RATIO'|±'PIXELS'::
	Set or change the splitting ratio of the edge located in the given direction in relation to the selected window.

*-R*, *--rotate* 'DIR' '90|270|180'::
	Rotate the tree holding the edge located in the given direction in relation to the selected window.

*-t*, *--state* tiled|pseudo_tiled|floating|fullscreen::
	Set the state of the selected window.

*-g*, *--flag* locked|sticky|private[=on|off]::
	Set or toggle the given flag for the selected window.

*-l*, *--layer* below|normal|above::
	Set the stacking layer of the selected window.

*-c*, *--close*::
	Close the selected window.

*-k*, *--kill*::
	Kill the selected window.

Desktop
~~~~~~~

General Syntax
^^^^^^^^^^^^^^

desktop ['DESKTOP_SEL'] 'OPTIONS'

Options
^^^^^^^
*-f*, *--focus* ['DESKTOP_SEL']::
	Focus the selected or given desktop.

*-m*, *--to-monitor* 'MONITOR_SEL'::
	Send the selected desktop to the given monitor.

*-l*, *--layout* 'CYCLE_DIR'|monocle|tiled::
	Set or cycle the layout of the selected desktop.

*-n*, *--rename* <new_name>::
	Rename the selected desktop.

*-s*, *--swap* 'DESKTOP_SEL'::
	Swap the selected desktop with the given desktop.

*-b*, *--bubble* 'CYCLE_DIR'::
	Bubble the selected desktop in the given direction.

*-r*, *--remove*::
	Remove the selected desktop.

*-c*, *--cancel-presel*::
	Cancel the preselection of all the windows of the selected desktop.

*-F*, *--flip* 'horizontal|vertical'::
	Flip the tree of the selected desktop.

*-R*, *--rotate* '90|270|180'::
	Rotate the tree of the selected desktop.

*-E*, *--equalize*::
	Reset the split ratios of the tree of the selected desktop.

*-B*, *--balance*::
	Adjust the split ratios of the tree of the selected desktop so that all windows occupy the same area.

*-C*, *--circulate* forward|backward::
	Circulate the leaves of the tree of the selected desktop.


Monitor
~~~~~~~

General Syntax
^^^^^^^^^^^^^^

monitor ['MONITOR_SEL'] 'OPTIONS'

Options
^^^^^^^
*-f*, *--focus* ['MONITOR_SEL']::
	Focus the selected or given monitor.

*-a*, *--add-desktops* <name>...::
	Create desktops with the given names in the selected monitor.

*-r*, *--remove-desktops* <name>...::
	Remove desktops with the given names.

*-o*, *--reorder-desktops* <name>...::
	Reorder the desktops of the selected monitor to match the given order.

*-d*, *--reset-desktops* <name>...::
	Rename, add or remove desktops depending on whether the number of given names is equal, superior or inferior to the number of existing desktops. Incidentally reset the settings of the existing desktops.

*-n*, *--rename* <new_name>::
	Rename the selected monitor.

*-s*, *--swap* 'MONITOR_SEL'::
	Swap the selected monitor with the given monitor.

Query
~~~~~

General Syntax
^^^^^^^^^^^^^^

query 'OPTIONS'

Options
^^^^^^^
*-W*, *--windows*::
	List the IDs of the matching windows.

*-D*, *--desktops*::
	List the names of the matching desktops.

*-M*, *--monitors*::
	List the names of the matching monitors.

*-T*, *--tree*::
	Print a JSON representation of the matching item.

*-H*, *--history*::
	Print the focus history as it relates to the query.

*-S*, *--stack*::
	Print the window stacking order.

[*-m*,*--monitor* ['MONITOR_SEL']] | [*-d*,*--desktop* ['DESKTOP_SEL']] | [*-w*, *--window* ['WINDOW_SEL']]::
	Constrain matches to the selected monitor, desktop or window.

Restore
~~~~~~~

General Syntax
^^^^^^^^^^^^^^

restore 'OPTIONS'

Options
^^^^^^^

*-T*, *--tree* <file_path>::
	Load the desktop trees from the given file.

*-H*, *--history* <file_path>::
	Load the focus history from the given file.

*-S*, *--stack* <file_path>::
	Load the window stacking order from the given file.

Control
~~~~~~~

General Syntax
^^^^^^^^^^^^^^

control 'OPTIONS'

Options
^^^^^^^

*--adopt-orphans*::
	Manage all the unmanaged windows remaining from a previous session.

*--toggle-visibility*::
	Toggle the visibility of all the windows.

*--record-history* on|off::
	Enable or disable the recording of window focus history.

*--subscribe* (all|report|monitor|desktop|window|...)*::
	Continuously print status information. See the *EVENTS* section for the detailed description of each event.

*--get-status*::
	Print the current status information.

Pointer
~~~~~~~

General Syntax
^^^^^^^^^^^^^^

pointer 'OPTIONS'

Options
^^^^^^^

*-g*, *--grab* focus|move|resize_side|resize_corner::
	Initiate the given pointer action.

*-t*, *--track* <x> <y>::
	Pass the pointer root coordinates for the current pointer action.

*-u*, *--ungrab*::
	Terminate the current pointer action.

Rule
~~~~

General Syntax
^^^^^^^^^^^^^^

rule 'OPTIONS'

Options
^^^^^^^

*-a*, *--add* <class_name>|<instance_name>|* [*-o*|*--one-shot*] [monitor=MONITOR_SEL|desktop=DESKTOP_SEL|window=WINDOW_SEL] [state=STATE] [layer=LAYER] [split_dir=DIR] [split_ratio=RATIO] [(locked|sticky|private|center|follow|manage|focus|border)=(on|off)]::
	Create a new rule.

*-r*, *--remove* ^<n>|head|tail|<class_name>|<instance_name>|*...::
	Remove the given rules.

*-l*, *--list* [<class_name>|<instance_name>|*]::
	List the rules.

Config
~~~~~~

General Syntax
^^^^^^^^^^^^^^

config [-m 'MONITOR_SEL'|-d 'DESKTOP_SEL'|-w 'WINDOW_SEL'] <key> [<value>]::
	Get or set the value of <key>.

Quit
~~~~

General Syntax
^^^^^^^^^^^^^^

quit [<status>]::
	Quit with an optional exit status.

Exit Codes
----------

If the server can't handle a message, *bspc* will return with one of the following exit codes:

1::
	Failure.
2::
	Syntax error.
3::
	Unknown command.


Settings
--------
Colors are either '#RRGGBB' or http://en.wikipedia.org/wiki/X11_color_names[X color names], booleans are 'true', 'on', 'false' or 'off'.

All the boolean settings are 'false' by default unless stated otherwise.

Global Settings
~~~~~~~~~~~~~~~

'focused_border_color'::
	Color of the border of a focused window of a focused monitor.

'active_border_color'::
	Color of the border of a focused window of an unfocused monitor.

'normal_border_color'::
	Color of the border of an unfocused window.

'presel_border_color'::
	Color of the *window --presel* message feedback.

'focused_locked_border_color'::
	Color of the border of a focused locked window of a focused monitor.

'active_locked_border_color'::
	Color of the border of a focused locked window of an unfocused monitor.

'normal_locked_border_color'::
	Color of the border of an unfocused locked window.

'focused_sticky_border_color'::
	Color of the border of a focused sticky window of a focused monitor.

'active_sticky_border_color'::
	Color of the border of a focused sticky window of an unfocused monitor.

'normal_sticky_border_color'::
	Color of the border of an unfocused sticky window.

'focused_private_border_color'::
	Color of the border of a focused private window of a focused monitor.

'active_private_border_color'::
	Color of the border of a focused private window of an unfocused monitor.

'normal_private_border_color'::
	Color of the border of an unfocused private window.

'urgent_border_color'::
	Color of the border of an urgent window.

'split_ratio'::
	Default split ratio.

'status_prefix'::
	Prefix prepended to each of the status lines.

'external_rules_command'::
	External command used to retrieve rule consequences. The command will receive the the ID of the window being processed as its first argument and the class and instance names as second and third arguments. The output of that command must have the following format: *key1=value1 key2=value2 ...* (the valid key/value pairs are given in the description of the 'rule' command).

'initial_polarity'::
	On which child should a new window be attached when adding a window on a single window tree in automatic mode. Accept the following values: *first_child*, *second_child*.

'history_aware_focus'::
	Give priority to the focus history when focusing nodes.

'focus_by_distance'::
	Base focusing on distances between windows.

'borderless_monocle'::
	Remove borders of tiled windows for the *monocle* desktop layout.

'gapless_monocle'::
	Remove gaps of tiled windows for the *monocle* desktop layout.

'leaf_monocle'::
	Set the desktop layout to *monocle* if there's only one tiled window in the tree.

'focus_follows_pointer'::
	Focus the window under the pointer.

'pointer_follows_focus'::
	When focusing a window, put the pointer at its center.

'pointer_follows_monitor'::
	When focusing a monitor, put the pointer at its center.

'auto_alternate'::
	Interpret consecutive identical *--focus* arguments as the *last* selector for the *monitor* and *desktop* commands.

'auto_cancel'::
	Interpret consecutive identical *--presel* arguments as *--cancel-presel* option.

'ignore_ewmh_focus'::
	Ignore EWMH focus requests coming from applications.

'center_pseudo_tiled'::
	Center pseudo tiled windows into their tiling rectangles. Defaults to 'true'.

'remove_disabled_monitors'::
	Consider disabled monitors as disconnected.

'remove_unplugged_monitors'::
	Remove unplugged monitors.

'merge_overlapping_monitors'::
	Merge overlapping monitors (the bigger remains).

Monitor and Desktop Settings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

'top_padding'::
'right_padding'::
'bottom_padding'::
'left_padding'::
	Padding space added at the sides of the monitor or desktop.

Default, Desktop Default and Window Settings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

'border_width'::
	Window border width.

Default and Desktop Settings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

'window_gap'::
	Size of the gap that separates windows.


Events
------

'report'::
	See the next section for the description of the format.

'monitor_add <monitor_name> <monitor_id> <monitor_geometry>'::
	A monitor is added.

'monitor_rename <old_name> <new_name>'::
	A monitor is renamed.

'monitor_remove <monitor_name>'::
	A monitor is removed.

'monitor_focus <monitor_name>'::
	A monitor is focused.

'monitor_geometry <monitor_name> <monitor_geometry>'::
	The geometry of a monitor changed.

'desktop_add <monitor_name> <desktop_name>'::
	A desktop is added.

'desktop_rename <monitor_name> <old_name> <new_name>'::
	A desktop is renamed.

'desktop_remove <monitor_name> <desktop_name>'::
	A desktop is removed.

'desktop_swap <src_monitor_name> <src_desktop_name> <dst_monitor_name> <dst_desktop_name>'::
	A desktop is swapped.

'desktop_transfer <src_monitor_name> <src_desktop_name> <dst_monitor_name>'::
	A desktop is transferred.

'desktop_focus <monitor_name> <desktop_name>'::
	A desktop is focused.

'desktop_layout <monitor_name> <desktop_name> tiled|monocle'::
	The layout of a desktop changed.

'window_manage <monitor_name> <desktop_name> <window_id> <ip_id>'::
	A window is managed.

'window_unmanage <monitor_name> <desktop_name> <window_id>'::
	A window is unmanaged.

'window_swap <src_monitor_name> <src_desktop_name> <src_window_id> <dst_monitor_name> <dst_desktop_name> <dst_window_id>'::
	A window is swapped.

'window_transfer <src_monitor_name> <src_desktop_name> <src_window_id> <dst_monitor_name> <dst_desktop_name> <dst_window_id>'::
	A window is transferred.

'window_focus <monitor_name> <desktop_name> <window_id>'::
	A window is focused.

'window_activate <monitor_name> <desktop_name> <window_id>'::
	A window is activated.

'window_geometry <monitor_name> <desktop_name> <window_id> <window_geometry>'::
	The geometry of a window changed.

'window_state <monitor_name> <desktop_name> <window_id> tiled|pseudo_tiled|floating|fullscreen on|off'::
	The state of a window changed.

'window_flag <monitor_name> <desktop_name> <window_id> sticky|private|locked|urgent on|off'::
	One of the flags of a window changed.

'window_layer <monitor_name> <desktop_name> <window_id> below|normal|above'::
	The layer of a window changed.

Please note that *bspwm* initializes monitors before it reads messages on its socket, therefore the initial monitor events can't be received.

Report Format
-------------

Each report event message is composed of items separated by colons.

Each item has the form '<type><value>' where '<type>' is the first character of the item.

'M<monitor_name>'::
	Focused monitor.

'm<monitor_name>'::
	Unfocused monitor.

'O<desktop_name>'::
	Occupied focused desktop.

'o<desktop_name>'::
	Occupied unfocused desktop.

'F<desktop_name>'::
	Free focused desktop.

'f<desktop_name>'::
	Free unfocused desktop.

'U<desktop_name>'::
	Urgent focused desktop.

'u<desktop_name>'::
	Urgent unfocused desktop.

'L(T|M)'::
	Layout of the focused desktop of a monitor.

Environment Variables
---------------------

'BSPWM_SOCKET'::
	The path of the socket used for the communication between *bspc* and *bspwm*. If it isn't defined, then the following path is used: '/tmp/bspwm<host_name>_<display_number>_<screen_number>-socket'.

Contributors
------------

* Steven Allen <steven at stebalien.com>
* Thomas Adam <thomas at xteddy.org>
* Ivan Kanakarakis <ivan.kanak at gmail.com>

Author
------

Bastien Dejean <nihilhill at gmail.com>
