#! /bin/sh

FIRST_DESK=One
REMAINING_DESKS='Two Three Four Five Six Seven Eight Nine Ten'
bspc rename Desktop01 $FIRST_DESK
bspc add $REMAINING_DESKS

bspc rule Gimp Eight floating

bspc set border_width        4
bspc set window_gap          12
bspc set borderless_monocle  true
bspc set gapless_monocle     true
bspc set adaptative_raise    true
